// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/db.proto

package db

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_db_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_api_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_api_db_proto_rawDescGZIP(), []int{1}
}

func (x *UserID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_db_proto protoreflect.FileDescriptor

const file_api_db_proto_rawDesc = "" +
	"\n" +
	"\fapi/db.proto\x12&github.com.PinguinAdvokat.akira_mcp.db\x1a\x1bgoogle/protobuf/empty.proto\"<\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\"\x18\n" +
	"\x06UserID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xc5\x01\n" +
	"\tDBService\x12O\n" +
	"\aAddUser\x12,.github.com.PinguinAdvokat.akira_mcp.db.User\x1a\x16.google.protobuf.Empty\x12g\n" +
	"\aGetUser\x12..github.com.PinguinAdvokat.akira_mcp.db.UserID\x1a,.github.com.PinguinAdvokat.akira_mcp.db.UserB3Z1github.com/PinguinAdvokat/akira-mcp/pkg/api/db;dbb\x06proto3"

var (
	file_api_db_proto_rawDescOnce sync.Once
	file_api_db_proto_rawDescData []byte
)

func file_api_db_proto_rawDescGZIP() []byte {
	file_api_db_proto_rawDescOnce.Do(func() {
		file_api_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_db_proto_rawDesc), len(file_api_db_proto_rawDesc)))
	})
	return file_api_db_proto_rawDescData
}

var file_api_db_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_db_proto_goTypes = []any{
	(*User)(nil),          // 0: github.com.PinguinAdvokat.akira_mcp.db.User
	(*UserID)(nil),        // 1: github.com.PinguinAdvokat.akira_mcp.db.UserID
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_api_db_proto_depIdxs = []int32{
	0, // 0: github.com.PinguinAdvokat.akira_mcp.db.DBService.AddUser:input_type -> github.com.PinguinAdvokat.akira_mcp.db.User
	1, // 1: github.com.PinguinAdvokat.akira_mcp.db.DBService.GetUser:input_type -> github.com.PinguinAdvokat.akira_mcp.db.UserID
	2, // 2: github.com.PinguinAdvokat.akira_mcp.db.DBService.AddUser:output_type -> google.protobuf.Empty
	0, // 3: github.com.PinguinAdvokat.akira_mcp.db.DBService.GetUser:output_type -> github.com.PinguinAdvokat.akira_mcp.db.User
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_db_proto_init() }
func file_api_db_proto_init() {
	if File_api_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_db_proto_rawDesc), len(file_api_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_db_proto_goTypes,
		DependencyIndexes: file_api_db_proto_depIdxs,
		MessageInfos:      file_api_db_proto_msgTypes,
	}.Build()
	File_api_db_proto = out.File
	file_api_db_proto_goTypes = nil
	file_api_db_proto_depIdxs = nil
}
