// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: connection/v1/connection.proto

package connectionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionResult_Status int32

const (
	ConnectionResult_STATUS_UNSPECIFIED ConnectionResult_Status = 0
	ConnectionResult_STATUS_OK          ConnectionResult_Status = 1
	ConnectionResult_STATUS_ERROR       ConnectionResult_Status = 2
	ConnectionResult_STATUS_TIMEOUT     ConnectionResult_Status = 3
	ConnectionResult_STATUS_REJECTED    ConnectionResult_Status = 4
)

// Enum value maps for ConnectionResult_Status.
var (
	ConnectionResult_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_ERROR",
		3: "STATUS_TIMEOUT",
		4: "STATUS_REJECTED",
	}
	ConnectionResult_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_ERROR":       2,
		"STATUS_TIMEOUT":     3,
		"STATUS_REJECTED":    4,
	}
)

func (x ConnectionResult_Status) Enum() *ConnectionResult_Status {
	p := new(ConnectionResult_Status)
	*p = x
	return p
}

func (x ConnectionResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_connection_v1_connection_proto_enumTypes[0].Descriptor()
}

func (ConnectionResult_Status) Type() protoreflect.EnumType {
	return &file_connection_v1_connection_proto_enumTypes[0]
}

func (x ConnectionResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionResult_Status.Descriptor instead.
func (ConnectionResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_connection_v1_connection_proto_rawDescGZIP(), []int{10, 0}
}

// ClientMessage — конверт для всех сообщений клиента.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Register
	//	*ClientMessage_Result
	//	*ClientMessage_Ping
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_connection_v1_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_connection_v1_connection_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ClientMessage) GetResult() *ConnectionResult {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ClientMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ClientMessage_Result struct {
	Result *ConnectionResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type ClientMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*ClientMessage_Register) isClientMessage_Payload() {}

func (*ClientMessage_Result) isClientMessage_Payload() {}

func (*ClientMessage_Ping) isClientMessage_Payload() {}

// ServerMessage — конверт для всех сообщений сервера.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_RegisterAck
	//	*ServerMessage_Connection
	//	*ServerMessage_Pong
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_connection_v1_connection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_connection_v1_connection_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetRegisterAck() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *ServerMessage) GetConnection() *Connection {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Connection); ok {
			return x.Connection
		}
	}
	return nil
}

func (x *ServerMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_RegisterAck struct {
	RegisterAck *RegisterResponse `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type ServerMessage_Connection struct {
	Connection *Connection `protobuf:"bytes,2,opt,name=connection,proto3,oneof"`
}

type ServerMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,3,opt,name=pong,proto3,oneof"`
}

func (*ServerMessage_RegisterAck) isServerMessage_Payload() {}

func (*ServerMessage_Connection) isServerMessage_Payload() {}

func (*ServerMessage_Pong) isServerMessage_Payload() {}

// RegisterRequest — первое сообщение при подключении.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id — уникальный идентификатор клиента (uuid). Обязателен.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// platform — целевая ОС: linux / darwin / windows.
	Platform      string `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_connection_v1_connection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_connection_v1_connection_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// RegisterResponse — подтверждение регистрации.
type RegisterResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// heartbeat_interval_ms — период отправки Ping клиентом.
	HeartbeatIntervalMs int64 `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_connection_v1_connection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_connection_v1_connection_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_connection_v1_connection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_connection_v1_connection_proto_rawDescGZIP(), []int{4}
}

func (x *Ping) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_connection_v1_connection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_connection_v1_connection_proto_rawDescGZIP(), []int{5}
}

func (x *Pong) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// connection — команда для исполнения клиентом. Поле id обязательно:
// клиент возвращает его в ConnectionResult.connection_id.
type Connection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Connection_Exec
	//	*Connection_ReadFile
	//	*Connection_WriteFile
	Payload   isConnection_Payload   `protobuf_oneof:"payload"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// timeout_ms — лимит исполнения; 0 означает без таймаута.
	TimeoutMs     int64 `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_connection_v1_connection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_connection_v1_connection_proto_rawDescGZIP(), []int{6}
}

func (x *Connection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Connection) GetPayload() isConnection_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Connection) GetExec() *ExecConnection {
	if x != nil {
		if x, ok := x.Payload.(*Connection_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *Connection) GetReadFile() *ReadFileRequest {
	if x != nil {
		if x, ok := x.Payload.(*Connection_ReadFile); ok {
			return x.ReadFile
		}
	}
	return nil
}

func (x *Connection) GetWriteFile() *WriteFileRequest {
	if x != nil {
		if x, ok := x.Payload.(*Connection_WriteFile); ok {
			return x.WriteFile
		}
	}
	return nil
}

func (x *Connection) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Connection) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type isConnection_Payload interface {
	isConnection_Payload()
}

type Connection_Exec struct {
	Exec *ExecConnection `protobuf:"bytes,2,opt,name=exec,proto3,oneof"`
}

type Connection_ReadFile struct {
	ReadFile *ReadFileRequest `protobuf:"bytes,3,opt,name=read_file,json=readFile,proto3,oneof"`
}

type Connection_WriteFile struct {
	WriteFile *WriteFileRequest `protobuf:"bytes,4,opt,name=write_file,json=writeFile,proto3,oneof"`
}

func (*Connection_Exec) isConnection_Payload() {}

func (*Connection_ReadFile) isConnection_Payload() {}

func (*Connection_WriteFile) isConnection_Payload() {}

// ExecConnection — запуск процесса.
type ExecConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecConnection) Reset() {
	*x = ExecConnection{}
	mi := &file_connection_v1_connection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecConnection) ProtoMessage() {}

func (x *ExecConnection) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecConnection.ProtoReflect.Descriptor instead.
func (*ExecConnection) Descriptor() ([]byte, []int) {
	return file_connection_v1_connection_proto_rawDescGZIP(), []int{7}
}

func (x *ExecConnection) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

// ReadFileRequest — прочитать файл и вернуть содержимое.
type ReadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// max_bytes — ограничение размера ответа; 0 = без ограничения.
	MaxBytes      int64 `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_connection_v1_connection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_connection_v1_connection_proto_rawDescGZIP(), []int{8}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileRequest) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

// WriteFileRequest — записать файл.
type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreateDirs    bool                   `protobuf:"varint,3,opt,name=create_dirs,json=createDirs,proto3" json:"create_dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_connection_v1_connection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_connection_v1_connection_proto_rawDescGZIP(), []int{9}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteFileRequest) GetCreateDirs() bool {
	if x != nil {
		return x.CreateDirs
	}
	return false
}

// ConnectionResult — результат исполнения команды.
type ConnectionResult struct {
	state        protoimpl.MessageState  `protogen:"open.v1"`
	ConnectionId string                  `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Status       ConnectionResult_Status `protobuf:"varint,2,opt,name=status,proto3,enum=akira.connection.v1.ConnectionResult_Status" json:"status,omitempty"`
	// exit_code — валиден только для ExecConnection.
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// stdout — валиден для ExecConnection и ReadFileRequest.
	Stdout []byte `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// stderr — валиден только для ExecConnection.
	Stderr []byte `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// error — текст ошибки при status = STATUS_ERROR.
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// duration_ms — фактическое время исполнения.
	DurationMs    int64 `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionResult) Reset() {
	*x = ConnectionResult{}
	mi := &file_connection_v1_connection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionResult) ProtoMessage() {}

func (x *ConnectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_connection_v1_connection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionResult.ProtoReflect.Descriptor instead.
func (*ConnectionResult) Descriptor() ([]byte, []int) {
	return file_connection_v1_connection_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectionResult) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectionResult) GetStatus() ConnectionResult_Status {
	if x != nil {
		return x.Status
	}
	return ConnectionResult_STATUS_UNSPECIFIED
}

func (x *ConnectionResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ConnectionResult) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ConnectionResult) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ConnectionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ConnectionResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_connection_v1_connection_proto protoreflect.FileDescriptor

const file_connection_v1_connection_proto_rawDesc = "" +
	"\n" +
	"\x1econnection/v1/connection.proto\x12\x13akira.connection.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x01\n" +
	"\rClientMessage\x12B\n" +
	"\bregister\x18\x01 \x01(\v2$.akira.connection.v1.RegisterRequestH\x00R\bregister\x12?\n" +
	"\x06result\x18\x02 \x01(\v2%.akira.connection.v1.ConnectionResultH\x00R\x06result\x12/\n" +
	"\x04ping\x18\x03 \x01(\v2\x19.akira.connection.v1.PingH\x00R\x04pingB\t\n" +
	"\apayload\"\xda\x01\n" +
	"\rServerMessage\x12J\n" +
	"\fregister_ack\x18\x01 \x01(\v2%.akira.connection.v1.RegisterResponseH\x00R\vregisterAck\x12A\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2\x1f.akira.connection.v1.ConnectionH\x00R\n" +
	"connection\x12/\n" +
	"\x04pong\x18\x03 \x01(\v2\x19.akira.connection.v1.PongH\x00R\x04pongB\t\n" +
	"\apayload\"f\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\"e\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x122\n" +
	"\x15heartbeat_interval_ms\x18\x02 \x01(\x03R\x13heartbeatIntervalMs\"\x18\n" +
	"\x04Ping\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\"\x18\n" +
	"\x04Pong\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\"\xc9\x02\n" +
	"\n" +
	"Connection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\x04exec\x18\x02 \x01(\v2#.akira.connection.v1.ExecConnectionH\x00R\x04exec\x12C\n" +
	"\tread_file\x18\x03 \x01(\v2$.akira.connection.v1.ReadFileRequestH\x00R\breadFile\x12F\n" +
	"\n" +
	"write_file\x18\x04 \x01(\v2%.akira.connection.v1.WriteFileRequestH\x00R\twriteFile\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x03R\ttimeoutMsB\t\n" +
	"\apayload\"\"\n" +
	"\x0eExecConnection\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\"B\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\x03R\bmaxBytes\"a\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1f\n" +
	"\vcreate_dirs\x18\x03 \x01(\bR\n" +
	"createDirs\"\xed\x02\n" +
	"\x10ConnectionResult\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12D\n" +
	"\x06status\x18\x02 \x01(\x0e2,.akira.connection.v1.ConnectionResult.StatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\fR\x06stderr\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\"j\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x02\x12\x12\n" +
	"\x0eSTATUS_TIMEOUT\x10\x03\x12\x13\n" +
	"\x0fSTATUS_REJECTED\x10\x042j\n" +
	"\x11ConnectionService\x12U\n" +
	"\aConnect\x12\".akira.connection.v1.ClientMessage\x1a\".akira.connection.v1.ServerMessage(\x010\x01BJZHgithub.com/PinguinAdvokat/akira-mcp/pkg/api/connectionpb/v1;connectionpbb\x06proto3"

var (
	file_connection_v1_connection_proto_rawDescOnce sync.Once
	file_connection_v1_connection_proto_rawDescData []byte
)

func file_connection_v1_connection_proto_rawDescGZIP() []byte {
	file_connection_v1_connection_proto_rawDescOnce.Do(func() {
		file_connection_v1_connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connection_v1_connection_proto_rawDesc), len(file_connection_v1_connection_proto_rawDesc)))
	})
	return file_connection_v1_connection_proto_rawDescData
}

var file_connection_v1_connection_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_connection_v1_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_connection_v1_connection_proto_goTypes = []any{
	(ConnectionResult_Status)(0),  // 0: akira.connection.v1.ConnectionResult.Status
	(*ClientMessage)(nil),         // 1: akira.connection.v1.ClientMessage
	(*ServerMessage)(nil),         // 2: akira.connection.v1.ServerMessage
	(*RegisterRequest)(nil),       // 3: akira.connection.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 4: akira.connection.v1.RegisterResponse
	(*Ping)(nil),                  // 5: akira.connection.v1.Ping
	(*Pong)(nil),                  // 6: akira.connection.v1.Pong
	(*Connection)(nil),            // 7: akira.connection.v1.Connection
	(*ExecConnection)(nil),        // 8: akira.connection.v1.ExecConnection
	(*ReadFileRequest)(nil),       // 9: akira.connection.v1.ReadFileRequest
	(*WriteFileRequest)(nil),      // 10: akira.connection.v1.WriteFileRequest
	(*ConnectionResult)(nil),      // 11: akira.connection.v1.ConnectionResult
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_connection_v1_connection_proto_depIdxs = []int32{
	3,  // 0: akira.connection.v1.ClientMessage.register:type_name -> akira.connection.v1.RegisterRequest
	11, // 1: akira.connection.v1.ClientMessage.result:type_name -> akira.connection.v1.ConnectionResult
	5,  // 2: akira.connection.v1.ClientMessage.ping:type_name -> akira.connection.v1.Ping
	4,  // 3: akira.connection.v1.ServerMessage.register_ack:type_name -> akira.connection.v1.RegisterResponse
	7,  // 4: akira.connection.v1.ServerMessage.connection:type_name -> akira.connection.v1.Connection
	6,  // 5: akira.connection.v1.ServerMessage.pong:type_name -> akira.connection.v1.Pong
	8,  // 6: akira.connection.v1.Connection.exec:type_name -> akira.connection.v1.ExecConnection
	9,  // 7: akira.connection.v1.Connection.read_file:type_name -> akira.connection.v1.ReadFileRequest
	10, // 8: akira.connection.v1.Connection.write_file:type_name -> akira.connection.v1.WriteFileRequest
	12, // 9: akira.connection.v1.Connection.created_at:type_name -> google.protobuf.Timestamp
	0,  // 10: akira.connection.v1.ConnectionResult.status:type_name -> akira.connection.v1.ConnectionResult.Status
	1,  // 11: akira.connection.v1.ConnectionService.Connect:input_type -> akira.connection.v1.ClientMessage
	2,  // 12: akira.connection.v1.ConnectionService.Connect:output_type -> akira.connection.v1.ServerMessage
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_connection_v1_connection_proto_init() }
func file_connection_v1_connection_proto_init() {
	if File_connection_v1_connection_proto != nil {
		return
	}
	file_connection_v1_connection_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Register)(nil),
		(*ClientMessage_Result)(nil),
		(*ClientMessage_Ping)(nil),
	}
	file_connection_v1_connection_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_RegisterAck)(nil),
		(*ServerMessage_Connection)(nil),
		(*ServerMessage_Pong)(nil),
	}
	file_connection_v1_connection_proto_msgTypes[6].OneofWrappers = []any{
		(*Connection_Exec)(nil),
		(*Connection_ReadFile)(nil),
		(*Connection_WriteFile)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connection_v1_connection_proto_rawDesc), len(file_connection_v1_connection_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connection_v1_connection_proto_goTypes,
		DependencyIndexes: file_connection_v1_connection_proto_depIdxs,
		EnumInfos:         file_connection_v1_connection_proto_enumTypes,
		MessageInfos:      file_connection_v1_connection_proto_msgTypes,
	}.Build()
	File_connection_v1_connection_proto = out.File
	file_connection_v1_connection_proto_goTypes = nil
	file_connection_v1_connection_proto_depIdxs = nil
}
